### ISSUE TITLE
Banco de Dados - Otimização das Tabelas

### ISSUE THREAD

**Issue by mfelipovsky** [sant0ro/matriculeMe#13]
**Esta issue descreve as otimizações feitas no banco de dados. Sendo apenas descrito os tipos de Otimizações realizados, e descritos nos comentários.**
1. Melhorias Léxicos/Sintaxe
2. Melhorias na Visualização do DER
3. Melhorias na Nomenclatura das Colunas/Tabelas
4. Melhorias nas Chaves Estrangeiras.

**Comment by ovflowd** [comment]
**ME-01**
Normalização da Coluna "Créditos" para "creditos".

**Comment by ovflowd** [comment]
**ME-02**
Normalização com LowerCase Pattern nas Nomenclaturas de Colunas e Tabelas.

**Comment by ovflowd** [comment]
**ME-03**
Melhorias e Atualizações no Conjunto de Tabelas Respectivos a Disciplinas (Disciplina, Curso, Departamento, Currículo)
_Alterou-se.:_ Colunas relacionadas a Disciplinas e Currículos.

**Comment by ovflowd** [comment]
**ME-04**
Melhorias na abordagem de armazenamento de Reservas de Matérias.

**Comment by ovflowd** [comment]
**ME-05**
Melhorias na Visualização das Tabelas e Alterações/Normalizações de FK's.

**Comment by ovflowd** [comment]
**ME-06**
Melhorias nas nomenclaturas de algumas colunas e reorganização da visualização.
_Obs.:_ Não foram feitas alterações na estrutura, apenas na organização.

**Comment by ovflowd** [comment]
**Fim de Atualizações.**
Apenas atualizações provenientes ao desenvolvimento do servidor ou fase de testes poderão acarretar em mudanças.

**Comment by ovflowd** [comment]
**ME-07**
Atualização de Modelagem.

Observação Crítica: Tabela Oferta POSSUÍ UM CAMPO DE VAGAS DESNECESSÁRIO. Devemos remover?

**Comment by ovflowd** [comment]
**ME-08**
Atualização crítica da Modelagem em Requisitos, Oferta, Histórico (Disciplinas Cursadas), Currículo, Disciplinas.
