### ISSUE TITLE
Banco de Dados - Tabelas de Logs do ML e IMW

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/matriculeMe#29]
Issue para descrever as necessidades de Tabelas do **Machine Learning (ML)** e **Integração Matrícula Web (IMW)**

Obs.: Discussão e Atualizações nos Comentários

**Comment by ovflowd** [comment]
**LG-01**
Inserção das Tabelas de Sugestão e Motivo da Sugestão.
_Observação.:_ Recomenda-se tabelas de Swap para o ML

**Comment by gustavogian** [comment]
![bandodedados](https://cloud.githubusercontent.com/assets/22320628/19487505/ed1996b2-9541-11e6-8ec3-9618374d7e94.png)

**Comment by gustavogian** [comment]
![bancodedados](https://cloud.githubusercontent.com/assets/22320628/19491748/e06121a4-9552-11e6-9a7c-861d664c754c.png)

**Comment by ghost** [comment]
![bancodedados](https://cloud.githubusercontent.com/assets/22320628/19682517/a9be3e5e-9a8c-11e6-9f53-efbcd3187987.png)
