### ISSUE TITLE
Definição do Cronograma

### ISSUE THREAD

**Issue by mfelipovsky** [sant0ro/matriculeMe#3]
Esta issue está relacionado a definição do **Cronograma do Projeto.** O Cronograma é um documento UML/XLS que designará como será o cronograma.

_Propostas de Cronograma serão publicadas por qui, através de imagens._

**Comment by ovflowd** [comment]
O Cronograma também deverá falar sobre as _Milestones_, me senti livre para criar a Milestone Atual, intitulada: Ciclo JaCheguei. Poderão mudar se quiser.

**Comment by ghost** [comment]
Não tenho certeza, mas acredito que o cronograma seja a última issue a ser finalizada, até porque ela tem como pré-requisito que a estrutura geral do projeto já esteja definida, é isso mesmo?

**Comment by mfelipovsky** [comment]
[GanttMatriculeMe.pdf](https://github.com/sant0ro/matriculeMe/files/499533/GanttMatriculeMe.pdf)

Vocês podem ver o cronograma nesse documento, o que eu fiz de diferente foi a divisão de cada etapa macro em subetapas para completá-las, peço que leiam, afinal todos precisam estar por dentro do cronograma.
