### ISSUE TITLE
Definição das Equipes

### ISSUE THREAD

**Issue by mfelipovsky** [sant0ro/matriculeMe#4]
Pessoal, até terça feira, quero que cada um de vocês pensem em qual das equipes querem ingressar. Eu pensei que para o correto funcionamento do sistema, as seguintes áreas serão necessárias:

**1 - Desenvolvimento Mobile (3 Pessoas):** Equipe que ficará responsável pelo desenvolvimento do aplicativo mobile que será utilizado pelo usuário do sistema.
**2 - Banco de Dados (2 Pessoas):** Equipe que ficará responsável pela estrutura do banco de dados, assim como no auxílio das outras equipes, quando estes necessitarem realizar conexões para buscar ou guardar algo no banco.
**3 - Interação com o MW (2 Pessoas):** Equipe responsável por extrair os dados de oferta e disciplinas do MW, assim como o histórico do aluno.
**4 - Machine Learning (3 Pessoas):** Equipe responsável por traçar o perfil do aluno, elaborando assim as sugestões de disciplinas que ele irá pegar.
**5 - Servidor (3 Pessoas):** Equipe que irá lidar com o servidor da aplicação, lidando com todas as interfaces de conexão remota entre usuário e sistema.

Peço que opinem com relação ao que pensei inicialmente, como o Gianini disse no tópico abaixo, é importante ter conhecimento e motivação na área. Caso você não tenha conhecimento em uma delas, e julgar interessante participar, busque aprender um pouco por conta própria, durante o andamento do projeto esse conhecimento irá se aprofundar.

Área de interesse:
- Desenvolvimento Mobile
  Danilo Gameiro
  Sanches
  Matheus
  Thiago
  Filipe
- Banco de Dados
  Danilo Gameiro
  Alessandra Telles
  Gustavo Gianini
  Sanches
  Matheus
  Thiago
  Filipe
  Claudio
  Bruno
- Interação com o MW
  Marcos Felipe
- Machine Learning
  Alessandra Telles
  Danilo Gameiro
  Sanches
  Thiago
  Filipe
- Servidor
  Nicolas
  Matheus
  Thiago
  Claudio
  Bruno

**Comment by ghost** [comment]
Lembremo-nos que os critérios principais para escolha de um membro para determinada equipe são: 
- Conhecimento
- Motivação

**Comment by MFeliposvky** [comment]
Lista de membros das equipes:
1-
.
.
.
2-
.
.
3-
.
.
4-
.
.
.
5-
.
.

**Comment by ovflowd** [comment]
**Creio que seja recomendado ainda ressaltar que:**
1. Cada equipe possuirá um Scrum Master (Líder da Equipe)
2. Os Scrum Masters realizam relatórios técnicos e gerenciais
3. Scrum Masters possuem reuniões semanais com o Gerente do Projeto (Marcos) e Mensais com o P.O. (Flávio) sobre a gerência do projeto, progressos, prazos e _Mindmap_ (Fluxo do Projeto)
4. Essa equipe de S.M. com G.P e P.O formam a **Equipe de Gerência do Projeto**

**Comment by ovflowd** [comment]
**Os líderes das equipes devem ser geralmente as pessoas que possuem experiência com a área relacionada a equipe..** Tais como.:
1. Machine Learning/Data Mining
2. Programação Avançada/Intermediária Java
3. Banco de Dados Relacionais (plz not pgsql)
4. Aplicativos Mobile
5. Gerência de Projeto

**Comment by conilas** [comment]
Não sei o que tenho que dizer exatamente, mas tenho interesse na parte de mexer com o servidor hehe

**Comment by conilas** [comment]
Ah! E o BD também, apesar de não ter muito ( N A D A) conhecimento, estou motivado a aprender. :D

**Comment by dmcsanches** [comment]
Posso ficar em  qualquer grupo, mas tenho interesse no machine learning. Aptidão em Java, Data Mining e SQL(pg e ms).

**Comment by mathwww** [comment]
Tenho interesse em desenvolvimento mobile, BD e Servidor

**Comment by ghost** [comment]
Tenho interesse em BD apesar de não ter conhecimento nenhum.

**Comment by FilipeAfonso** [comment]
Tenho preferência máxima em trabalhar na área de desenvolvimento mobile (tenho experiência mínima na área, para não dizer nenhuma); não sendo possível, machine learning seria minha segunda opção, e BD, a terceira.

**Comment by ovflowd** [comment]
Okay, pelo que entendi,
@aletelles está com vontade de Machine Learning
@dmcsanches está com vontade de Data Mining e DB
@FilipeAfonso está com vontade de Mobile
@mathwww está com vontade de Servidor
@conilas está com vontade de Servidor

**O resto dos membros deverão se voluntariar em o que querem fazer**

**1ª chamada**
1. **Servidor:** (Servidor Principal Java) @conilas @mathwww @sant0ro
2. **Mobile:** (Aplicativo Principal) @FilipeAfonso (Precisa de mais duas pessoas)
3. **Machine Learning/Data Mining:** (Workers que mineram os Perfis, etc..) @aletelles @dmcsanches (Precisa de mais uma pessoa)
4. **Banco de Dados:** @sant0ro @dmcsanches 
5. **Interação com MW:** (Precisa de mais duas Pessoas)
6. **Gerência do Projeto e Artefatos:** @MFeliposvky (Precisa de mais duas pessoas)

Outros??

**Comment by AdonayVeiga** [comment]
Tenho aptidão para qualquer atividade de análise e projeto **lógico**, com interesse em algoritmos. Não me dou muito bem com Java, mas em último caso posso ajudar, _se for realmente necessário_.

Não tínhamos decidido que machine learning seria deixado para o futuro por falta de dados para processamento?

**Comment by ThiagoPita** [comment]
Tenho interesse em machine learning, Banco de dados, desenvolvimento mobile e servidor, mas não tenho experiencia com nenhuma dessas areas.

**Comment by ovflowd** [comment]
@ThiagoPita irei te colocar no Mobile, OK?
@AdonayVeiga Parece que decidimos que iremos fazer. ^^

**Comment by BrunoEmerich** [comment]
Bom dia a todos, tenho o interesse de fica na equipe do servidor alem de tambem querer mecher com o banco de dados(para aprender mesmo), pois acho uma area do projeto bem legal.

**Comment by ovflowd** [comment]
**2ª chamada**
1. **Servidor:** (Servidor Principal Java) @conilas @mathwww @sant0ro @BrunoEmerich 
2. **Mobile:** (Aplicativo Principal) @FilipeAfonso @ThiagoPita @DaniloGameiro 
3. **Machine Learning/Data Mining:** (Workers) @aletelles @dmcsanches 
4. **Banco de Dados:** @sant0ro @dmcsanches @FilipeAfonso 
5. **Interação com MW:** @MFeliposvky @DaniloGameiro @AdonayVeiga 
6. **Gerência do Projeto e Artefatos:** @MFeliposvky (Precisa de mais duas pessoas)

Outros??

**Comment by ovflowd** [comment]
**Chamada Final**
1. **Servidor:** (Servidor Principal Java) @conilas @mathwww @BrunoEmerich 
2. **Mobile:** (Aplicativo Principal) @FilipeAfonso @ThiagoPita 
3. **Machine Learning/Data Mining:** (Workers) @aletelles @DaniloGameiro @dmcsanches 
4. **Banco de Dados:** @sant0ro @gustavogian @DaniloGameiro 
5. **Interação com MW:** @MFeliposvky @AdonayVeiga 
6. **Gerência do Projeto e Artefatos:** @MFeliposvky @aletelles @conilas @FilipeAfonso @sant0ro

Outros??

**Comment by AdonayVeiga** [comment]
**Alterado em reunião do dia 04/10**
1. **Servidor:** (Servidor Principal Java) @conilas @mathwww @BrunoEmerich 
2. **Mobile:** (Aplicativo Principal) @FilipeAfonso @ThiagoPita @AdonayVeiga
3. **Machine Learning/Data Mining:** (Workers) @aletelles @DaniloGameiro @dmcsanches 
4. **Banco de Dados:** @sant0ro @gustavogian @DaniloGameiro 
5. **Interação com MW:** @MFeliposvky  
6. **Gerência do Projeto e Artefatos:** @MFeliposvky @aletelles @conilas @FilipeAfonso @sant0ro

**Comment by ovflowd** [comment]
@DaniloGameiro você confirma estar também no Machine Learning?
