### ISSUE TITLE
Definição dos Requisitos funcionais

### ISSUE THREAD

**Issue by ghost** [sant0ro/matriculeMe#5]

**Comment by FilipeAfonso** [comment]
[FuncionalidadesRFs.xlsx](https://github.com/sant0ro/matriculeMe/files/488717/FuncionalidadesRFs.xlsx)

Acima está um pequeno arquivo em Excel que retrata brevemente os RFs relativos a determinadas funcionalidades descritas no documento Requisitos.docx que o Marcos já disponibilizou aqui (por "1ª funcionalidade" entenda-se a funcionalidade enumerada por 1.1 no documento do Marcos, e assim por diante). De fato, este arquivo é direcionado ao Bruno, que ficou de estruturar a memória do que foi feito na aula de hoje (22/09/2016, quinta-feira).

**Comment by BrunoEmerich** [comment]
Felipe muito obrigado pelo arquivo. Estarei usando ele para fazer o relatorio da reuniao da ultima aula !!!

**Comment by mathwww** [comment]
Todos concordam com essas funcionalidades ? Alguém gostaria de acrescentar/retirar/sugerir mais alguma ?
