### ISSUE TITLE
Definição das Ferramentas Utilizadas

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/matriculeMe#6]
**Essa issue é destinada a descrever quais programas/metodologias/bibliotecas/ferramentas serão utilizadas para o desenvolvimento do projeto.:**
1. **Ferramentas de Produção de Software**
   1. **Java:**  JetBrains IntelliJ
   2. **Banco de Dados:** Navicat Premium ou JetBrains DataGrip
   3. **Aplicativo Mobile:** Android Studio ou Ionic
   4. **Outros?**
2. **Bibliotecas Utilizadas**
   1. **Machine Learning:**
   2. **Data Mining**
   3. **Servidor Principal**
   4. **Workers**
   5. **Aplicativo Mobile**
   6. **Banco de Dados**
3. **Metodologias**
   1. **Gerência de Projeto:** Agile
   2. **Outros?**
4. **Softwares Utilizados**
   1. **Aplicativo Mobile:** Ionic?
   2. **Machine Learning:** Apache Mahout
   3. **Data Mining:** Apache Mahout
   4. **Servidor Principal:**
   5. **Workers:**
   6. **Banco de Dados:** MariaDB ou Apache CouchDB?

_Esta issue poderá sofrer alterações, e será destinada também a discussão de quais ferramentas/etc serão utilizadas._

**Comment by ovflowd** [comment]
**Este comentário deverá ser atualizado com os Links de Referências dos Itens Apresentados:**

_Apache Mahout:_ http://mahout.apache.org/
_MariaDB (Baseado em MySQL):_ https://mariadb.org/
_Apache CouchDB:_ http://couchdb.apache.org/
_Ionic Framework:_ http://ionicframework.com/

**Comment by ghost** [comment]
O grupo Banco de Dados definiu as seguintes ferramentas:
- MariaDB (implementado em Linux OS)
- JetBrains DataGrip
- Astah (Ferramenta para criação da UML)
