### ISSUE TITLE
Definição do Modelo do Banco de Dados

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/matriculeMe#7]
**Esta Issue tem como responsabilidade definir o Modelo (Schema) do Banco de Dados. Deve ser utilizado uma fermenta UML.**
1. Definição da Arquitetura
2. Definição das Entidades
3. Definição dos Atores
4. Design Reverso?

**Comment by ghost** [comment]
Esboço! Comentem no Slack ou Whatsapp!

![image](https://cloud.githubusercontent.com/assets/22320628/19043568/1287b190-8967-11e6-9573-cd8cb82cf0f2.png)
